name: image_size_getter
description: Get image width and height, the library does not completely decode the image file, just read the metadata to get the image width and height.
version: 2.1.1
homepage: https://github.com/CaiJingLong/dart_image_size_getter/tree/master/library
# publish_to: https://pub.dev

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  collection: ^1.14.13
  hashcodes: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
